### PR TITLE
pass job_tags and session_id kwargs correctly

### PR DESCRIPTION
**Pull request by lillian542**
A user on the forum was trying to pass `job_tags` and `session_id` to the `circuit_runner` device, unsuccessfully. 

They were being included in generic runtime kwargs and passed to the runtime service in the `program_inputs` argument, which doesn't work; `job_tags` belongs in the `options` dictionary, and `session_id` is its own kwarg on `runtime_service.run`. Now they will be passed to the correct places.

### CODE REVIEW

**Comment by lillian542** [comment]
[sc-52032]

**Review by mudit2812 — COMMENTED** [review]
Doesn't matter too much but is it possible to add testing for this?

**Comment by lillian542** [comment]
Maybe if I try hard enough, but it looks like currently we don't test that kwargs **work** in the tests, just that passing them to the device doesn't cause the circuit to **fail**, so it would be a bit unprecedented.

I tried getting the information from `dev._current_job`, because that would be a quick and easy addition to the tests, but it doesn't include this in the metadata, so I'm not sure where/if I can access it, or if its just stored in their database for task retrieval.

Here's a screenshot where you can see that my tag ("now with a session") and session id were registered when the task ran.

image

**Review by mudit2812 — APPROVED** [review]
Thanks for checking! Looks good. Here's a 🚀

**Review by timmysilv — APPROVED** [review]
nice!

**Pull request merged**
