### PR TITLE
Remove ibmq devices

### PR DESCRIPTION
**Pull request by austingmhuang**
After discussion with @trbromley, it was decided to remove these devices. This PR simply deletes all the devices and where they are referenced in the docs/code. No other changes were needed.

### CODE REVIEW

**Comment by austingmhuang** [comment]
[sc-63583]

**Review by obliviateandsurrender — APPROVED** [review]
It looks good to me. Few points -
1. We are removing them without any deprecation cycle? 
2. We should check whether our demos depend on these devices.
3. Is there any replacement for these devices from Qiskit's side? Or is it just the `remote` devices?

**Comment by austingmhuang** [comment]
> It looks good to me. Few points -
> 
> 1. We are removing them without any deprecation cycle?

Yes. There are a lot of reasons as to why but basically yes.

> 2. We should check whether our demos depend on these devices.

This is a good point.

> 3. Is there any replacement for these devices from Qiskit's side? Or is it just the `remote` devices?

Just the remote devices. Sampler/Circuit-runner (raw samples) are replaced with SamplerV2, which is what we are going to use going forward as well.

**Review by lillian542 — APPROVED** [review]
Is there a story for updating the demos?

**Comment by austingmhuang** [comment]
> Is there a story for updating the demos?

No, not yet. I'll create a story for that.

**Pull request merged**
