### PR TITLE
Add a projector observable to QiskitDevice

### PR DESCRIPTION
**Pull request by wongwsvincent**
Context:
Adding a projector observable to QiskitDevice.

Description of the Change:
Adding ```Projector``` to the list of observables compatible with QiskitDevice in ```qiskit_device.py```.

Related GitHub PR:
Work coherently with PR [#1356](https://github.com/PennyLaneAI/pennylane/pull/1356)

### CODE REVIEW

**Comment by wongwsvincent** [comment]
@josh146 , I added docstrings here because I saw CodeFactor in the github workflow was complaining about not having docstrings under the functions. I'm not sure why the docstrings weren't inherited from the parent class, and I'm not familiar enough with Sphinx to understand why. The flagged issues can be found [here](https://github.com/PennyLaneAI/pennylane-qiskit/pull/137/checks?check_run_id=2682260099).

Could you give me a bit of help here?

**Comment by josh146** [comment]
> I saw CodeFactor in the github workflow was complaining about not having docstrings under the functions

Thanks for flagging this @wongwsvincent --- it appears that Codefactor is incorrect here, and these particular methods do not need docstrings.

Feel free to remove them, even if codefactor complains about the missing docstrings, I will be able to overwrite those :)

**Comment by wongwsvincent** [comment]
Thanks for clarifying, @josh146 ! I have removed the docstrings.

**Review by josh146 — APPROVED** [review]
Thanks @wongwsvincent! Good to go now 💯

**Pull request merged**
